[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_transito = "N4JdhqzrojrrXhzMYvyAS9smq3Ekp7nuHKpZ1YuhXy6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
